const languages = {
	en: {
		// Other sections...
		login: {
			header: "Login",
			email: "Email",
			password: "Password",
			submit: "Login",
			error_user_not_found: "User not found",
			error_wrong_password: "Wrong password",
		},
		logout: {
			header: "Logout",
			submit: "Logout",
		},
		addUsers: {
			header: "Add Users",
			firstName: "First Name",
			lastName: "Last Name",
			email: "Email",
			id: "ID",
			phone: "Phone Number",
			submit: "Add",
			chooseFile: "Choose File",
		},
		addAgudaMembers: {
			header: "Add A Member",
			firstName: "First Name",
			lastName: "Last Name",
			position: "Position",
			img: "Image Link",
			submit: "Add",
		},
		addEvent: {
			header: "Add Event",
			title: "Title",
			description: "Description",
			date: "Date",
			time: "Time",
			chooseFile: "Choose File",
			submit: "Add",
		},
		addMarathon: {
			header: "Add Marathon",
			department: "Department",
			course: "Course",
			lecturer: "Lecturer",
			date: "Date",
			price: "Price",
			currency: "₪",
			link: "Registration Link",
			submit: "Add",
		},
		deleteAgudaMembers: {
			header: "Delete Aguda Member",
			firstName: "First Name",
			lastName: "Last Name",
			submit: "Delete",
		},
		manageAgudaMembers: {
			header: "Manage Aguda Members",
		},
		manageEvents: {
			header: "Manage Events",
		},
		manageMarathons: {
			header: "Manage Marathons",
		},
		navBar: {
			header: "Admin Panel",
			home: "Home",
			manageAgudaMembers: "Manage Aguda Members",
			manageEvents: "Manage Events",
			manageMarathons: "Manage Marathons",
			manageUsers: "Manage Users",
		},
	},
	he: {
		// Other sections...
		login: {
			header: "התחברות",
			email: "אימייל",
			password: "סיסמה",
			submit: "התחבר",
			error_user_not_found: "משתמש לא נמצא",
			error_wrong_password: "סיסמה שגויה",
		},
		logout: {
			header: "התנתקות",
			submit: "התנתק",
		},
		addUsers: {
			header: "הוספת משתמשים",
			firstName: "שם פרטי",
			lastName: "שם משפחה",
			email: "אימייל",
			id: "תעודת זהות",
			phone: "מספר טלפון",
			submit: "הוסף",
			chooseFile: "בחר קובץ",
		},
		addAgudaMembers: {
			header: "הוספת חבר אגודה",
			firstName: "שם פרטי",
			lastName: "שם משפחה",
			position: "תפקיד",
			img: "קישור לתמונה",
			submit: "הוסף",
		},
		addEvent: {
			header: "הוספת אירוע",
			title: "כותרת",
			description: "תיאור",
			date: "תאריך",
			time: "שעה",
			chooseFile: "בחר קובץ",
			submit: "הוסף",
		},
		addMarathon: {
			header: "הוספת מרתון",
			department: "מחלקה",
			course: "קורס",
			lecturer: "מרצה",
			date: "תאריך",
			price: "מחיר",
			currency: "₪",
			link: "קישור להרשמה",
			submit: "הוסף",
		},
		deleteAgudaMembers: {
			header: "מחיקת חבר אגודה",
			firstName: "שם פרטי",
			lastName: "שם משפחה",
			submit: "מחק",
		},
		manageAgudaMembers: {
			header: "ניהול חברי אגודה",
		},
		manageEvents: {
			header: "ניהול אירועים",
		},
		manageMarathons: {
			header: "ניהול מרתונים",
		},
		navBar: {
			header: "פאנל ניהול",
			home: "בית",
			manageAgudaMembers: "ניהול חברי אגודה",
			manageEvents: "ניהול אירועים",
			manageMarathons: "ניהול מרתונים",
			manageUsers: "ניהול משתמשים",
		},
	},
};

export default languages;
